### ISSUE TITLE
base values on css-type-base

### ISSUE THREAD

**Issue by yoshuawuyts** [stackcss/css-scale#1]
``` css
:root {
  --base-font-size: 22;
  --base-line-height: 1.5;
  --leading: calc(var(--base-line-height) * 1rem);
  --scale: 1.414;
}
```
